### ISSUE TITLE
Resolve version mismatch for datepickers

### ISSUE THREAD

**Issue by mbohal** [synergic-cz/synergic-ui#26]
Synergic UI depends on eonasdan-bootstrap-datetimepicker 3.x.x, but datetime picker depends on the latest version of moment.js. Latest moment.js is however not compatible with eonasdan-bootstrap-datetimepicker 3.x.x.

We need to either hardcode the required versions of both eonasdan-bootstrap-datetimepicker and moment.js in Synergic UI or convicne the author of eonasdan-bootstrap-datetimepicker to not depend on latest moment.js. Namely the author should not use >=x.x.x but ~x.x.x.

**Comment by adamkudrna** [comment]
Upgraded to datetimepicker 4.x in the meantime. Shall we also notify the datepicker's author? Or close this issue right away?

**Comment by mbohal** [comment]
Since the error is related to an old version of a package and we are not using it anymore I dont think we should bother with it. Lets close it.

**Comment by adamkudrna** [comment]
OK but we should be aware that `>=x.x.x` is still there, even in 4.x.
